In [50]:
# Project 6 Train And Test Data

import pandas as pd
import numpy as np
prices = [
    100, 102, 104, 101, 98,
    105, 110, 108, 112, 115,
    109, 107, 111, 117, 120,
    118, 121, 125, 123, 128,
    130, 127, 132, 135, 138,
    136, 140, 145, 143, 148
]

df = pd.DataFrame({'Prices' : prices})

data_split = int(len(prices) * 0.7)
results = []


train_df = pd.DataFrame(df.iloc[:data_split])
test_df = pd.DataFrame(df.iloc[data_split:])
train_df

train_df['Return'] = train_df['Prices'].pct_change()

for fast in range(2,6):
    for slow in range(6,11):
        train_df['Fast_MA']= train_df['Prices'].rolling(window=fast).mean()
        train_df['Slow_MA']= train_df['Prices'].rolling(window=slow).mean()
        train_df['Signal'] = np.where(train_df['Fast_MA'] > train_df['Slow_MA'] , 1,0)
        train_df['Strategy_Return'] = train_df['Signal'].shift(1)*train_df['Return']
        sharpe = train_df['Strategy_Return'].mean()/ train_df['Strategy_Return'].std()
        results.append([fast,slow,sharpe])
        
        
train_df
results
train_df1 = pd.DataFrame(results,columns=['Fast','Slow','Sharpe'])
train_df1.sort_values(by='Sharpe',ascending=False,inplace=True)
train_df1
best_fast = train_df1['Fast'].iloc[0]
best_slow = train_df1['Slow'].iloc[0]

test_df['Fast_MA'] = test_df['Prices'].rolling(window=best_fast).mean()
test_df['Slow_MA'] = test_df['Prices'].rolling(window=best_slow).mean()
test_df['Return'] = test_df['Prices'].pct_change()
test_df['Signal'] = np.where(test_df['Fast_MA'] > test_df['Slow_MA'],1,0)
test_df['Strategy_Return'] = test_df['Signal'].shift(1)*test_df['Return']
test_df['Equity_Curve'] = (1 + test_df['Strategy_Return']).cumprod()
test_df['Drawdown'] = (test_df['Equity_Curve'] - test_df['Equity_Curve'].cummax())/test_df['Equity_Curve'].cummax()
sharpe = test_df['Strategy_Return'].mean()/test_df['Strategy_Return'].std()
#mssj = jsu_df['Hi Hello Bye Bye','Yes No Bye Tye','Keep Dont,','Kiosk In Out','Susbstantua',']


max_drawdown = test_df['Drawdown'].min()
print(sharpe)
test_df

0.393673570294693

,Prices,Fast_MA,Slow_MA,Return,Signal,Strategy_Return,Equity_Curve,Drawdown
21,127,NaN,NaN,NaN,0,NaN,NaN,NaN
22,132,NaN,NaN,0.039370,0,0.000000,1.000000,0.000000
23,135,NaN,NaN,0.022727,0,0.000000,1.000000,0.000000
24,138,NaN,NaN,0.022222,0,0.000000,1.000000,0.000000
25,136,133.6,NaN,-0.014493,0,-0.000000,1.000000,0.000000
26,140,136.2,134.666667,0.029412,1,0.000000,1.000000,0.000000
27,145,138.8,137.666667,0.035714,1,0.035714,1.035714,0.000000
28,143,140.4,139.500000,-0.013793,1,-0.013793,1.021429,-0.013793
29,148,142.4,141.666667,0.034965,1,0.034965,1.057143,0.000000

In [5]:
# Proect 7 Transaction Cost

import pandas as pd
import numpy as np
prices = [
    100, 102, 104, 101, 98,
    105, 110, 108, 112, 115,
    109, 107, 111, 117, 120,
    118, 121, 125, 123, 128,
    130, 127, 132, 135, 138,
    136, 140, 145, 143, 148
]

df = pd.DataFrame({'Prices' : prices})

data_split = int(len(prices) * 0.7)
results = []
final_results = []


train_df = pd.DataFrame(df.iloc[:data_split])
test_df = pd.DataFrame(df.iloc[data_split:])
final_test_df = pd.DataFrame(df.iloc[data_split:])

train_df

train_df['Return'] = train_df['Prices'].pct_change()

for fast in range(2,6):
    for slow in range(6,11):
        train_df['Fast_MA']= train_df['Prices'].rolling(window=fast).mean()
        train_df['Slow_MA']= train_df['Prices'].rolling(window=slow).mean()
        train_df['Signal'] = np.where(train_df['Fast_MA'] > train_df['Slow_MA'] , 1,0)
        train_df['Strategy_Return'] = train_df['Signal'].shift(1)*train_df['Return']
        train_df['Final_Strategy_Return'] = np.where(train_df['Signal'] != train_df['Signal'].shift(1),train_df['Signal'].shift(1)*train_df['Return'] - 0.001,train_df['Signal'].shift(1)*train_df['Return'])
        sharpe = (train_df['Strategy_Return'].mean())/ train_df['Strategy_Return'].std()
        final_sharpe = (train_df['Final_Strategy_Return'].mean())/ train_df['Final_Strategy_Return'].std()
        results.append([fast,slow,sharpe])
        final_results.append([fast,slow,final_sharpe])
        
        
train_df
results
train_df1 = pd.DataFrame(results,columns=['Fast','Slow','Sharpe'])
final_train_df1 = pd.DataFrame(final_results,columns=['Fast','Slow','Final Sharpe'])

train_df1.sort_values(by='Sharpe',ascending=False,inplace=True)
final_train_df1.sort_values(by='Final Sharpe',ascending=False,inplace=True)

train_df1
best_fast = train_df1['Fast'].iloc[0]
best_slow = train_df1['Slow'].iloc[0]
final_best_fast = final_train_df1['Fast'].iloc[0]
final_best_slow = final_train_df1['Slow'].iloc[0]



test_df['Fast_MA'] = test_df['Prices'].rolling(window=best_fast).mean()
test_df['Slow_MA'] = test_df['Prices'].rolling(window=best_slow).mean()
test_df['Return'] = test_df['Prices'].pct_change()
test_df['Signal'] = np.where(test_df['Fast_MA'] > test_df['Slow_MA'],1,0)
test_df['Strategy_Return'] = test_df['Signal'].shift(1)*test_df['Return']

test_df['Equity_Curve'] = (1 + test_df['Strategy_Return']).cumprod()
test_df['Drawdown'] = (test_df['Equity_Curve'] - test_df['Equity_Curve'].cummax())/test_df['Equity_Curve'].cummax()
sharpe = test_df['Strategy_Return'].mean()/test_df['Strategy_Return'].std()
#mssj = jsu_df['Hi Hello Bye Bye','Yes No Bye Tye','Keep Dont,','Kiosk In Out','Susbstantua',']

final_test_df['Fast_MA'] = final_test_df['Prices'].rolling(window=final_best_fast).mean()
final_test_df['Slow_MA'] = final_test_df['Prices'].rolling(window=final_best_slow).mean()
final_test_df['Return'] = final_test_df['Prices'].pct_change()
final_test_df['Signal'] = np.where(final_test_df['Fast_MA'] > final_test_df['Slow_MA'],1,0)
final_test_df['Final_Strategy_Return'] = np.where(final_test_df['Signal']!=final_test_df['Signal'].shift(1),final_test_df['Signal'].shift(1)*final_test_df['Return'] - 0.001,final_test_df['Signal'].shift(1)*final_test_df['Return'])

test_df['Equity_Curve'] = (1 + test_df['Strategy_Return']).cumprod()
final_test_df['Equity_Curve'] = (1 + final_test_df['Final_Strategy_Return']).cumprod()
test_df['Drawdown'] = (test_df['Equity_Curve'] - test_df['Equity_Curve'].cummax())/test_df['Equity_Curve'].cummax()
final_test_df['Drawdown'] = (final_test_df['Equity_Curve'] - final_test_df['Equity_Curve'].cummax())/final_test_df['Equity_Curve'].cummax()
sharpe = test_df['Strategy_Return'].mean()/test_df['Strategy_Return'].std()
final_sharpe = final_test_df['Final_Strategy_Return'].mean()/final_test_df['Final_Strategy_Return'].std()

#mssj = jsu_df['Hi Hello Bye Bye','Yes No Bye Tye','Keep Dont,','Kiosk In Out','Susbstantua',']


max_drawdown = test_df['Drawdown'].min()
final_max_drawdown = final_test_df['Drawdown'].min()
print(sharpe)
#test_df
final_test_df

0.393673570294693

,Prices,Fast_MA,Slow_MA,Return,Signal,Strategy_Return,Equity_Curve,Drawdown
21,127,NaN,NaN,NaN,0,NaN,NaN,NaN
22,132,NaN,NaN,0.039370,0,0.000000,1.000000,0.000000
23,135,NaN,NaN,0.022727,0,0.000000,1.000000,0.000000
24,138,NaN,NaN,0.022222,0,0.000000,1.000000,0.000000
25,136,133.6,NaN,-0.014493,0,-0.000000,1.000000,0.000000
26,140,136.2,134.666667,0.029412,1,0.000000,1.000000,0.000000
27,145,138.8,137.666667,0.035714,1,0.035714,1.035714,0.000000
28,143,140.4,139.500000,-0.013793,1,-0.013793,1.021429,-0.013793
29,148,142.4,141.666667,0.034965,1,0.034965,1.057143,0.000000